sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
addons:
  firefox: "45.0"
before_script:
  # Chrome
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update && sudo apt-get install google-chrome-stable
  - sh -e /etc/init.d/xvfb start
  # Start chrome to initialize profile
  - google-chrome &
  - CHROME_PID=$!
  # Libsodium
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update && sudo apt-get install -y libsodium-dev
  # Create test certificate for localhost
  - openssl req -new -newkey rsa:1024 -nodes -sha256 -out saltyrtc.csr -keyout saltyrtc.key -subj '/C=CH/O=SaltyRTC/CN=localhost/'
  - openssl x509 -req -days 365 -in saltyrtc.csr -signkey saltyrtc.key -out saltyrtc.crt
  # Add certificate to firefox and chrome
  - kill $CHROME_PID
  - sudo apt-get install -y libnss3-tools
  - mkdir ~/.mozilla/firefox/saltyrtc
  - certutil -d ~/.mozilla/firefox/saltyrtc -A -n saltyrtc-test-ca -t Ccw,, -i saltyrtc.crt
  - certutil -d sql:$HOME/.pki/nssdb -A -n saltyrtc-test-ca -t Ccw,, -i saltyrtc.crt
  # Start SaltyRTC server
  - git clone https://github.com/saltyrtc/saltyrtc-server-python -b master
  - export SALTYRTC_TLS_CERT=../saltyrtc.crt SALTYRTC_TLS_KEY=../saltyrtc.key
  - export SALTYRTC_SERVER_PERMANENT_KEY=0919b266ce1855419e4066fc076b39855e728768e3afa773105edd2e37037c20
  - |
    cd saltyrtc-server-python
    pyvenv venv
    venv/bin/python setup.py install
    venv/bin/pip install logbook
    venv/bin/python examples/debug.py > serverlog.txt 2>&1 &
    export SALTYRTC_SERVER_PID=$!
    sleep 2
    cd ..
  # Rollup tests
  - npm install
  - npm run rollup_tests
script:
  - npm test
  - |
    mv tsconfig.json tsconfig.ignore
    node_modules/.bin/tsc --target ES2015 --noEmit saltyrtc/main.ts
    mv tsconfig.ignore tsconfig.json
after_script:
  # Stop SaltyRTC server
  - kill -INT $SALTYRTC_SERVER_PID
  # Print server log
  - |
    echo "---------- Server Log ----------\n"
    cat saltyrtc-server-python/serverlog.txt
    echo -e "\n---------- End Server Log ----------"
  # Build docs
  - bash scripts/travis_build_docs.sh
  - ls -la ~/.mozilla/firefox
env:
  global:
    - secure: "mWKQu4QlYcEO7G6o2hYOKaeZV/+NXDcHu1OJok6BCEmyT1G6ExCNP7+mzKbzhNm7LTAjl14KzPolB4306+xj1k67ssFQ7nGm+GmEvYQQ8AsVVBTpnAUDDKE65VJHqRXSTeBAnv3JAlFGXHDSCHbhX02CW+rW8L8XJD9ZdkKyuQYZ42h83hDqBs8hYxoX7DHOwigmohYUcYvRMH1Eh/Y3VOOQ6mCYN+BZ5ppryC/HaCMkiIC0G1azVo5XqNMaMZ5QZ8qDdYGclFZB8yFc89whUoXk+JeT/PVgakoPS8Tb9MAzm1b+fz1xfk9CGRLNcp9ZluohQiacrWxmKOsTqfaiE1eoU/wrDsRw7bXZTEskHL1aBlOssRirLmyHLOvPOxsz4mGfs6gTRWayeOv1x4vDQuw8VODfwRfioxok10E+a85Ow8i/2HsBkWXynN7NanXqerBtat4fmIM+5UQB2g3+F3eFaF/15BRil8dMA384fUuhXd2e9YyNN5gh3Y/ehKRI5nae73cq5l2D/MntjZBgvQe7//qT6IJfSylwFIafD2+kAEe+8AYKRTtDyjgkGWB1tmuRkLiwuEch+ezaV/17gNyqciDh6gN89+1D0IzgN3RdVRqmJTvh/R/09m3A1mu24ZI3eaJ92nWkaCVacfQo76O0yvimM9cW6JDz6mn8YQ8="
