site_name: SaltyRTC Client for JavaScript
site_description: Documentation for saltyrtc-client-js.
site_author: Threema GmbH
copyright: Â© 2016-2022 Threema GmbH
theme: readthedocs
repo_url: https://github.com/saltyrtc/saltyrtc-client-js
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - smarty
  - toc:
      permalink: False
pages:
  - Home: index.md
  - Guide:
    - Installing: installing.md
    - Usage: usage.md
  - About: about.md
